#############
### INPUT ###
#############

#https://wiki.hypr.land/Configuring/Variables/#input

input {
  kb_layout = us
  kb_variant = 
  kb_model = 
  kb_options = 
  kb_rules = 

  # Move focus on mouse hover.
  follow_mouse = true

  # [-1.0 -> +1.0]
  sensitivity = 0

  touchpad {
    natural_scroll = false
  }
}


gensture = 3, horizontal, workspace


device {
  name = yichip-wireless-device-mouse
  sensitivity = -0.9
}




