# https://wiki.hypr.land/Configuring/

source = ./monitor.conf
source = ./programs.conf
source = ./autostart.conf
source = ./environment.conf
source = ./permission.conf
source = ./looks.conf
source = ./input.conf
source = ./keybind.conf
source = ./windowrule.conf
